ALTER TABLE merchant
  ADD COLUMN IF NOT EXISTS store_phone VARCHAR(20) NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS line_id VARCHAR(100) NULL AFTER type,
  ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255) NULL AFTER line_id;
