CREATE TABLE IF NOT EXISTS merchant_preferences (
  merchant_id INT NOT NULL,
  order_notification TINYINT(1) NOT NULL DEFAULT 1,
  auto_hide_menu TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
