CREATE TABLE IF NOT EXISTS merchant_loyalty_settings (
  merchant_id INT NOT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  baht_per_point INT UNSIGNED NOT NULL DEFAULT 50,
  points_for_discount INT UNSIGNED NOT NULL DEFAULT 100,
  discount_amount DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 10.00,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
